version: '3.8'

services:
  frontend:
    image: frontend
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
