version: '3.8'

services:
  backend:
    image: backend
    build:
      context: ./backend
    ports:
      - "8081:8081"
    networks:
      - monitoring-net

  frontend:
    image: frontend
    build:
      context: ./frontend
    ports:
      - "8000:8000"
    networks:
      - monitoring-net   

networks:
  monitoring-net:
    driver: bridge