version: '3.8'

services:
  frontend:
    image: your-frontend-image
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - monitoring-net

  backend:
    image: your-backend-image
    build:
      context: ./backend
    ports:
      - "8081:8081"
    networks:
      - monitoring-net

networks:
  monitoring-net:
    driver: bridge
