version: '3.8'

services:
  backend:
    image: backend
    build:
      context: .
    ports:
      - "8081:8081"
    networks:
      - monitoring-net
    

networks:
  monitoring-net:
    driver: bridge